# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WH-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WH-iOS
pod ‘RxSwift’, ‘~> 5’
pod ‘RxCocoa’, ‘~> 5’
pod 'RxFlow'
pod 'ReactorKit'
pod ‘Alamofire’, ‘~> 5.2’
pod 'Kingfisher', '~> 5.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'RxDataSources', '~> 4.0'
pod 'SOTabBar'
pod 'Moya', '~> 14.0'
pod 'Moya/RxSwift', '~> 14.0'
pod 'KMPlaceholderTextView', '~> 1.4.0'

end
